#!/usr/bin/env python

# FIXME: sometimes this program segfaults on start up
#        i have no idea why it happens

from argparse import ArgumentParser
from PySide6.QtWidgets import (
  QApplication,
  QMainWindow,
  QDialog,
  QWidget,
  QVBoxLayout,
  QLabel,
  QPushButton,
  QProgressBar,
  QStatusBar,
  QMessageBox,
  QMenuBar,
  QMenu,
  QStyle,
)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebChannel import QWebChannel
from PySide6.QtCore import (
  QUrl,
  QObject,
  Slot,
  Signal,
  Qt,
  QTimer,
  QEvent,
)
from PySide6.QtGui import (
  QCloseEvent,
  QKeyEvent,
  QShortcut,
  QAction,
  QKeySequence,
  QIcon,
)
from annotation_file import (
  annotation_parse,
  AnnotationFile,
  PlainAnnotation,
  LoanAnnotation,
  KanjiAnnotation,
  Annotation,
  annotation_save,
)
from dataclasses import dataclass
from normal_word_db import NormalWordList, load_normal_words
from loan_word_db import LoanWordList, load_loan_words
import animecho_rc
import html
from typing import override
import enum
from enum import Enum

@dataclass
class UserNormalDictionary:
  inner: NormalWordList
  path: str

@dataclass
class UserLoanDictionary:
  inner: LoanWordList
  path: str

class AnimechoWebBridge(QObject):
  # -- called from web into native --
  webLoadFinished = Signal()
  webCalledback = Signal(int, int)

  # -- called from native into web --
  nativeUpdateContent = Signal(str, bool)

  # -- glues for web-native calls --

  @Slot()
  def notifyNativeLoadFinished(self):
    self.webLoadFinished.emit()

  @Slot(int, int)
  def notifyNativeCalledback(self, lidx: int, aidx: int):
    self.webCalledback.emit(lidx, aidx)

class WaitingWebDialog(QDialog):
  # XXX: is this really useful? does it work?

  def __init__(self, parent: QWidget):
    QDialog.__init__(self, parent)

    self.__can_quit = False

    self.__layout = QVBoxLayout(self)

    self.__lbl_indicator = QLabel(text='Waiting for internal Web view to boot...')
    self.__spinner = QProgressBar(maximum=0)
    self.__btn_quit = QPushButton('Quit App Now')

    self.__btn_quit.clicked.connect(self.__do_quit_app)

    self.__layout.addWidget(self.__lbl_indicator)
    self.__layout.addWidget(self.__spinner)
    self.__layout.addWidget(self.__btn_quit)

  @override
  def closeEvent(self, event: QCloseEvent):
    if self.__can_quit:
      QDialog.closeEvent(self, event)
      return

    print('you cant close this dialog, please hit the quit app button instead')
    event.ignore()

  @override
  def keyPressEvent(self, event: QKeyEvent):
    if event.key() != Qt.Key.Key_Escape:
      QDialog.keyPressEvent(self, event)
      return

    print('you cant close this dialog, please hit the quit app button instead')
    event.ignore()

  @Slot()
  def __do_quit_app(self):
    self.__can_quit = True
    self.reject()
    QApplication.quit()

  def tryCloseNormally(self):
    if self.result() == QDialog.DialogCode.Accepted:
      return

    self.__can_quit = True
    self.accept()

class CreateSegmentType(Enum):
  CREATE_KANJI_SEGMENT = enum.auto()
  CREATE_LOAN_SEGMENT = enum.auto()
  CREATE_IGNORE_SEGMENT = enum.auto()

class SelectSegmentTypeDialog(QDialog):
  def __init__(self, parent: QWidget):
    QDialog.__init__(self, parent)

    self.__result = None

    self.__layout = QVBoxLayout()

    self.__lbl_tip = QLabel('[1]. Label Kanji word...\n'
                            '[2]. Label loan word...\n'
                            '[3]. Ignore segment...')

    self.__btn_cancel = QPushButton('Cancel')
    self.__btn_cancel.clicked.connect(self.__do_cancel)

    self.__layout.addWidget(self.__lbl_tip)
    self.__layout.addWidget(self.__btn_cancel)

    self.setLayout(self.__layout)

    self.__key_create_kanji = QShortcut(Qt.Key.Key_1, self)
    self.__key_create_kanji.activated.connect(self.__do_create_kanji)

    self.__key_create_loan = QShortcut(Qt.Key.Key_2, self)
    self.__key_create_loan.activated.connect(self.__do_create_loan)

    self.__key_create_ignore = QShortcut(Qt.Key.Key_3, self)
    self.__key_create_ignore.activated.connect(self.__do_create_ignore)

  @Slot()
  def __do_create_kanji(self):
    self.__result = CreateSegmentType.CREATE_KANJI_SEGMENT
    self.accept()

  @Slot()
  def __do_create_loan(self):
    self.__result = CreateSegmentType.CREATE_LOAN_SEGMENT
    self.accept()

  @Slot()
  def __do_create_ignore(self):
    self.__result = CreateSegmentType.CREATE_IGNORE_SEGMENT
    self.accept()

  @Slot()
  def __do_cancel(self):
    self.reject()

  def getCreateSegmentType(self) -> CreateSegmentType:
    assert self.__result is not None
    return self.__result

class CutterStage(Enum):
  STAGE_A = enum.auto()
  STAGE_B = enum.auto()

class CutterDialog(QDialog):
  def __init__(self, parent: QWidget, text: str):
    QDialog.__init__(self, parent)

    self.__text = text

    self.__sel_a = 0
    self.__sel_b = len(text)
    self.__stage = CutterStage.STAGE_A

    self.__layout = QVBoxLayout()

    self.__lbl_tip = QLabel('Arrows to select, ENTER to commit, ESC to cancel.')
    self.__lbl_preview = QLabel()

    self.__layout.addWidget(self.__lbl_tip)
    self.__layout.addWidget(self.__lbl_preview)

    self.setLayout(self.__layout)

    self.__rerender_preview()

    self.__key_cursor_left = QShortcut(Qt.Key.Key_Left, self)
    self.__key_cursor_left.activated.connect(self.__do_move_cursor_left)

    self.__key_cursor_right = QShortcut(Qt.Key.Key_Right, self)
    self.__key_cursor_right.activated.connect(self.__do_move_cursor_right)

    self.__key_commit = QShortcut(Qt.Key.Key_Return, self)
    self.__key_commit.activated.connect(self.__do_commit)

  @Slot()
  def __do_commit(self):
    match self.__stage:
      case CutterStage.STAGE_A:
        self.__stage = CutterStage.STAGE_B
        self.__rerender_preview()
      case CutterStage.STAGE_B:
        self.accept()

  @Slot()
  def __do_move_cursor_left(self):
    match self.__stage:
      case CutterStage.STAGE_A:
        if self.__sel_a == 0:
          print('invalid move')
          return
        self.__sel_a -= 1
      case CutterStage.STAGE_B:
        if self.__sel_b == self.__sel_a + 1:
          print('must select at least one char')
          return
        self.__sel_b -= 1

    self.__rerender_preview()

  @Slot()
  def __do_move_cursor_right(self):
    match self.__stage:
      case CutterStage.STAGE_A:
        if self.__sel_a == self.__sel_b - 1:
          print('must select at least one char')
          return
        self.__sel_a += 1
      case CutterStage.STAGE_B:
        if self.__sel_b == len(self.__text):
          print('invalid move')
          return
        self.__sel_b += 1

    self.__rerender_preview()

  def __rerender_preview(self):
    chunks = []

    match self.__stage:
      case CutterStage.STAGE_A:
        indicator = '<font color="blue">▶　</font>'
      case CutterStage.STAGE_B:
        indicator = '<font color="blue">◀　</font>'
      case _:
        raise AssertionError()

    chunks.append(indicator)

    if self.__sel_a != 0:
      chunks.append(f'<span>{html.escape(self.__text[:self.__sel_a])}</span>')

    chunks.append(f'<font color="red">{html.escape(self.__text[self.__sel_a:self.__sel_b])}</font>')

    if self.__sel_b != len(self.__text):
      chunks.append(f'<span>{html.escape(self.__text[self.__sel_b:])}</span>')

    self.__lbl_preview.setText(''.join(chunks))

  def getSelectionRange(self) -> tuple[int, int]:
    return self.__sel_a, self.__sel_b

class AnnotationEdit(QMainWindow):
  def __init__(self, af: AnnotationFile, annotation_path: str, nwls: list[UserNormalDictionary], lwls: list[UserLoanDictionary]):
    QMainWindow.__init__(self)

    self.resize(600, 700)
    self.setWindowTitle(f'[*] {annotation_path}')

    self.__af = af
    self.__annotation_path = annotation_path

    self.__nwls = nwls
    self.__lwls = lwls

    self.__status_bar = QStatusBar()

    self.__lbl_unsaved = QLabel('UNSAVED')
    self.__lbl_unsaved.setVisible(False)

    self.__status_bar.addWidget(self.__lbl_unsaved)

    self.setStatusBar(self.__status_bar)

    self.__loading_dlg = WaitingWebDialog(self)

    # give enough time for webview to load
    self.__startup_debounce = QTimer(singleShot=True, interval=1000)
    self.__startup_debounce.timeout.connect(self.__startup_debounce_finished)

    self.__menubar = QMenuBar()

    self.__menu_file = QMenu(title='File')

    self.__action_save = QAction(text='Save',
                                 enabled=False,
                                 icon=self.style().standardIcon(QStyle.StandardPixmap.SP_DialogSaveButton),
                                 shortcut=QKeySequence.StandardKey.Save)
    self.__action_save.triggered.connect(self.__do_save)

    self.__action_quit = QAction(text='Quit',
                                 shortcut=QKeySequence.StandardKey.Quit,
                                 icon=QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
    self.__action_quit.triggered.connect(self.__do_quit)

    self.__menu_file.addAction(self.__action_save)
    self.__menu_file.addSeparator()
    self.__menu_file.addAction(self.__action_quit)

    self.__menubar.addMenu(self.__menu_file)

    self.setMenuBar(self.__menubar)

    self.__web_loaded = False

    self.__web = AnimechoWebBridge()

    self.__web.webLoadFinished.connect(self.__handle_web_load_finished)
    self.__web.webCalledback.connect(self.__handle_web_calledback)

    self.__webchan = QWebChannel()
    self.__webchan.registerObject('animecho', self.__web)

    self.__central_widget = QWidget()
    self.__webview = QWebEngineView(self.__central_widget)

    # hack to prevent flicker
    self.__webview.setGeometry(0, 0, 1, 1)

    self.__webview.setUrl(QUrl('qrc:/animecho/animecho.html'))
    self.__webview.page().setWebChannel(self.__webchan)

    self.setCentralWidget(self.__central_widget)

  @override
  @Slot()
  def show(self):
    QMainWindow.show(self)
    self.__loading_dlg.open()

  @override
  def changeEvent(self, event: QEvent):
    if event.type() == QEvent.Type.PaletteChange:
      # light/dark theme change
      # for some reasons we need to refresh web page
      # for theme change to apply in web view
      print('theme changed')
      self.__webview.reload()

    QMainWindow.changeEvent(self, event)

  def __rerender_animecho(self, restore_scroll: bool = False):
    tags = []

    for lidx, line in enumerate(self.__af.lines):
      tags.append('<p>')

      for aidx, annotation in enumerate(line.fragments):
        if isinstance(annotation.inner, PlainAnnotation):
          if annotation.unfinished:
            tags.append(f'<span class="animecho-unfinished" onclick="animechoCb({lidx},{aidx})">{html.escape(annotation.inner.text)}</span>')
          else:
            assert annotation.ignore
            tags.append(f'<span class="animecho-ignore">{html.escape(annotation.inner.text)}</span>')
        elif isinstance(annotation.inner, LoanAnnotation):
          tags.append(f'<span>{html.escape(annotation.inner.base)}</span>')
        elif isinstance(annotation.inner, KanjiAnnotation):
          tags.append('<span>')

          for chars in annotation.inner.fragments:
            tags.append(f'<span>{html.escape(chars.base)}</span>')

          tags.append('</span>')
        else:
          raise AssertionError('unhandled annotation type')

      tags.append('</p>')

    self.__web.nativeUpdateContent.emit(''.join(tags), restore_scroll)

  @Slot()
  def __startup_debounce_finished(self):
    # since we set size to 1x1 on startup to prevent flickers
    # we have to update it to current window size
    size = self.size()
    self.__webview.setGeometry(0, 0, size.width(), size.height())

    self.__loading_dlg.tryCloseNormally()

  @Slot()
  def __handle_web_load_finished(self):
    if self.__web_loaded:
      print('web reloaded')
      self.__rerender_animecho(restore_scroll=True)
    else:
      print('web is up')
      self.__rerender_animecho()
      self.__startup_debounce.start()
      self.__web_loaded = True

  def __update_ux_dirty(self, dirty: bool):
    self.__lbl_unsaved.setVisible(dirty)
    self.setWindowModified(dirty)
    self.__action_save.setEnabled(dirty)

  @Slot()
  def __do_save(self):
    self.__af.validate()

    with open(self.__annotation_path, 'w') as f:
      f.write(annotation_save(self.__af))
      f.write('\n')

    print('saved annotation file')

    self.__update_ux_dirty(False)

  @Slot()
  def __do_quit(self):
    self.close()

  @override
  def closeEvent(self, event: QCloseEvent):
    if not self.isWindowModified():
      print('quitting editor window')
      QMainWindow.closeEvent(self, event)
      return

    print('attempted to quit with unsaved changes!')

    pressed = QMessageBox.question(self, None,
                                   'The file is MODIFIED, '
                                   'and is NOT SAVED yet. '
                                   'You will LOSE them if you quit now, procceed anyway?',
                                   defaultButton=QMessageBox.StandardButton.No)

    if pressed == QMessageBox.StandardButton.Yes:
      print('quit with unsaved changes')
      event.accept()
    else:
      print('user canceled quit')
      event.ignore()

  @Slot(int, int)
  def __handle_web_calledback(self, lidx: int, aidx: int):
    dialogue = self.__af.lines[lidx]

    annotation = dialogue.fragments[aidx]

    assert annotation.unfinished
    assert isinstance(annotation.inner, PlainAnnotation)

    old_text = annotation.inner.text

    print(f'selected fragment: {old_text!r}')

    sstd = SelectSegmentTypeDialog(self)
    if sstd.exec() == QDialog.DialogCode.Rejected:
      print('user canceled')
      return

    cutter = CutterDialog(self, old_text)
    if cutter.exec() == QDialog.DialogCode.Rejected:
      print('user canecled')
      return

    sel = cutter.getSelectionRange()
    sel_text = old_text[sel[0]:sel[1]]

    match sstd.getCreateSegmentType():
      case CreateSegmentType.CREATE_IGNORE_SEGMENT:
        print(f'ignore: {sel_text!r}')
        new_annotation = Annotation(inner=PlainAnnotation(sel_text), ignore=True)
      case _:
        raise AssertionError

    # now, actually modify AF object

    new_annotations = []

    if sel[0] != 0:
      new_annotations.append(Annotation(inner=PlainAnnotation(old_text[:sel[0]]), unfinished=True))

    new_annotations.append(new_annotation)

    if sel[1] != len(old_text):
      new_annotations.append(Annotation(inner=PlainAnnotation(old_text[sel[1]:]), unfinished=True))

    dialogue.fragments.pop(aidx)
    dialogue.fragments[aidx:aidx] = new_annotations

    self.__rerender_animecho()
    self.__update_ux_dirty(True)

def main():
  ap = ArgumentParser()

  ap.add_argument('annotation_file')
  ap.add_argument('--dictionary', '-d', action='append', default=[], help='use WordDB. can pass multiple')
  ap.add_argument('--loan-dictionary', '-l', action='append', default=[], help='use loanword WordDB. can pass multiple')

  args = ap.parse_args()

  with open(args.annotation_file, 'r') as f:
    af = annotation_parse(f.read())

  nwls = [UserNormalDictionary(inner=load_normal_words(x), path=x) for x in args.dictionary]
  lwls = [UserLoanDictionary(inner=load_loan_words(x), path=x) for x in args.loan_dictionary]

  app = QApplication()
  ae = AnnotationEdit(af, args.annotation_file, nwls, lwls)
  ae.show()
  app.exec()

main()
