#!/usr/bin/env python
from argparse import ArgumentParser
from PySide6.QtWidgets import (
  QApplication,
  QMainWindow,
  QDialog,
  QWidget,
  QVBoxLayout,
  QLabel,
  QPushButton,
)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWebChannel import QWebChannel
from PySide6.QtCore import (
  QUrl,
  QObject,
  Slot,
  Signal,
  Qt,
)
from PySide6.QtGui import (
  QCloseEvent,
  QKeyEvent,
)
from annotation_file import (
  annotation_parse,
  AnnotationFile,
)
from dataclasses import dataclass
from normal_word_db import NormalWordList, load_normal_words
from loan_word_db import LoanWordList, load_loan_words
import animecho_rc

@dataclass
class UserNormalDictionary:
  inner: NormalWordList
  path: str

@dataclass
class UserLoanDictionary:
  inner: LoanWordList
  path: str

class AnimechoWebBridge(QObject):
  webLoadFinished = Signal()

  @Slot()
  def notifyNativeLoadFinished(self):
    self.webLoadFinished.emit()

class WaitingWebDialog(QDialog):
  def __init__(self, parent: QWidget):
    QDialog.__init__(self, parent)

    self.__can_quit = False

    self.__layout = QVBoxLayout(self)

    self.__lbl_indicator = QLabel(text='Waiting for internal Web view to boot...')
    self.__btn_quit = QPushButton('Quit App Now')

    self.__btn_quit.clicked.connect(self.__do_quit_app)

    self.__layout.addWidget(self.__lbl_indicator)
    self.__layout.addWidget(self.__btn_quit)

  def closeEvent(self, event: QCloseEvent):
    if self.__can_quit:
      QDialog.closeEvent(self, event)
      return

    print('you cant close this dialog, please hit the quit app button instead')
    event.ignore()

  def keyPressEvent(self, event: QKeyEvent):
    if event.key() != Qt.Key.Key_Escape:
      QDialog.keyPressEvent(self, event)
      return

    print('you cant close this dialog, please hit the quit app button instead')
    event.ignore()

  @Slot()
  def __do_quit_app(self):
    self.__can_quit = True
    self.reject()
    QApplication.quit()

  def tryCloseNormally(self):
    if self.result() == QDialog.DialogCode.Accepted:
      return

    self.__can_quit = True
    self.accept()

class AnnotationEdit(QMainWindow):
  def __init__(self, af: AnnotationFile, annotation_path: str, nwls: list[UserNormalDictionary], lwls: list[UserLoanDictionary]):
    QMainWindow.__init__(self)

    self.__af = af
    self.__annotation_path = annotation_path

    self.__nwls = nwls
    self.__lwls = lwls

    self.__loading_dlg = WaitingWebDialog(self)

    self.__web = AnimechoWebBridge()

    self.__web.webLoadFinished.connect(self.__handle_web_load_finished)

    self.__webchan = QWebChannel()
    self.__webchan.registerObject('animecho', self.__web)

    self.__webview = QWebEngineView()
    self.__webview.setUrl(QUrl('qrc:/animecho/animecho.html'))
    self.__webview.page().setWebChannel(self.__webchan)

    self.setCentralWidget(self.__webview)

  @Slot()
  def show(self):
    QMainWindow.show(self)
    self.__loading_dlg.open()

  @Slot()
  def __handle_web_load_finished(self):
    print('web is up')

    self.__loading_dlg.tryCloseNormally()

def main():
  ap = ArgumentParser()

  ap.add_argument('annotation_file')
  ap.add_argument('--dictionary', '-d', action='append', default=[], help='use WordDB. can pass multiple')
  ap.add_argument('--loan-dictionary', '-l', action='append', default=[], help='use loanword WordDB. can pass multiple')

  args = ap.parse_args()

  with open(args.annotation_file, 'r') as f:
    af = annotation_parse(f.read())

  nwls = [UserNormalDictionary(inner=load_normal_words(x), path=x) for x in args.dictionary]
  lwls = [UserLoanDictionary(inner=load_loan_words(x), path=x) for x in args.loan_dictionary]

  app = QApplication()
  ae = AnnotationEdit(af, args.annotation_file, nwls, lwls)
  ae.show()
  app.exec()

main()
