#!/usr/bin/env python
from argparse import ArgumentParser
from PySide6.QtWidgets import (
  QApplication,
  QMainWindow,
  QLabel,
)
from PySide6.QtCore import (
  Qt,
)
from normal_word_db import load_normal_words, NormalWordList
from loan_word_db import load_loan_words, LoanWordList

class DictViewer(QMainWindow):
  def __init__(self, nwl: NormalWordList, dict_path: str, lwl: LoanWordList, loan_dict_path: str):
    QMainWindow.__init__(self)

    self.__nwl = nwl
    self.__dict_path = dict_path
    self.__lwl = lwl
    self.__loan_dict_path = loan_dict_path

    self.__lbl_tip = QLabel(text='1. add new kanji word\n'
                                 '2. add new eng word',
                            alignment=Qt.AlignmentFlag.AlignCenter)

    self.setCentralWidget(self.__lbl_tip)

def main():
  ap = ArgumentParser()

  ap.add_argument('--dictionary-file', '-f', required=True)
  ap.add_argument('--loan-dictionary', '-l', required=True)

  args = ap.parse_args()

  nwl = load_normal_words(args.dictionary_file)
  lwl = load_loan_words(args.loan_dictionary)

  app = QApplication()
  dv = DictViewer(nwl, args.dictionary_file, lwl, args.dictionary_file)
  dv.show()
  app.exec()

main()
