#!/usr/bin/env python
from argparse import ArgumentParser
from PySide6.QtWidgets import (
  QApplication,
  QMainWindow,
  QLabel,
  QDialog,
  QWidget,
  QVBoxLayout,
  QLineEdit,
)
from PySide6.QtCore import (
  Qt,
  Slot,
)
from PySide6.QtGui import (
  QShortcut,
  QKeySequence,
)
from normal_word_db import load_normal_words, NormalWordList
from loan_word_db import load_loan_words, LoanWordList, append_into_loan_words, LoanWordAlreadyExist, LoanWord, reload_into_loan_words

class InputBaseWordDialog(QDialog):
  def __init__(self, parent: QWidget):
    QDialog.__init__(self, parent)

    self.__layout = QVBoxLayout(self)
    self.__edit = QLineEdit()
    self.__layout.addWidget(self.__edit)

    self.__result = ''

    self.__edit.returnPressed.connect(self.__do_commit)

  @Slot()
  def __do_commit(self):
    self.__result = self.__edit.text()

    if self.__result == '':
      print('word cannot be empty')
      return

    self.done(QDialog.DialogCode.Accepted)

  def getBaseWordResult(self) -> str:
    assert self.__result != ''
    return self.__result

class InputRomanizedWordDialog(QDialog):
  def __init__(self, parent: QWidget, base: str):
    QDialog.__init__(self, parent)

    self.__layout = QVBoxLayout(self)

    self.__hint_base = QLineEdit(text=base)
    self.__hint_base.setEnabled(False)

    self.__edit = QLineEdit()

    self.__layout.addWidget(self.__hint_base)
    self.__layout.addWidget(self.__edit)

    self.__result = ''

    self.__edit.returnPressed.connect(self.__do_commit)

  @Slot()
  def __do_commit(self):
    self.__result = self.__edit.text()

    if self.__result == '':
      print('word cannot be empty')
      return

    self.done(QDialog.DialogCode.Accepted)

  def getLoanWordResult(self) -> str:
    assert self.__result != ''
    return self.__result

class DictViewer(QMainWindow):
  def __init__(self, nwl: NormalWordList, dict_path: str, lwl: LoanWordList, loan_dict_path: str):
    QMainWindow.__init__(self)

    self.__nwl = nwl
    self.__dict_path = dict_path
    self.__lwl = lwl
    self.__loan_dict_path = loan_dict_path

    self.__lbl_tip = QLabel(text='1. add new kanji word\n'
                                 '2. add new eng word',
                            alignment=Qt.AlignmentFlag.AlignCenter)

    self.setCentralWidget(self.__lbl_tip)

    self.__key_new_word = QShortcut(Qt.Key.Key_1, self)
    self.__key_new_word.activated.connect(self.__do_new_word)

    self.__key_new_loan = QShortcut(Qt.Key.Key_2, self)
    self.__key_new_loan.activated.connect(self.__do_new_loan)

    self.__key_quit = QShortcut(QKeySequence.StandardKey.Cancel, self)
    self.__key_quit.activated.connect(self.__do_quit)

  @Slot()
  def __do_new_word(self):
    print('new word')

    ibwd = InputBaseWordDialog(self)
    if ibwd.exec() == QDialog.DialogCode.Rejected:
      print('user canceled')
      return

    base = ibwd.getBaseWordResult()
    print(f'base: {base!r}')

  @Slot()
  def __do_new_loan(self):
    print('new loan')

    ibwd = InputBaseWordDialog(self)
    if ibwd.exec() == QDialog.DialogCode.Rejected:
      print('user canceled')
      return

    base = ibwd.getBaseWordResult()
    print(f'base: {base!r}')

    irwd = InputRomanizedWordDialog(self, base)
    if irwd.exec() == QDialog.DialogCode.Rejected:
      print('user canceled')
      return

    romanized = irwd.getLoanWordResult()
    print(f'romanized: {romanized!r}')

    reload_into_loan_words(self.__lwl, self.__loan_dict_path)
    try:
      append_into_loan_words(self.__lwl, self.__loan_dict_path, LoanWord(base=base, romanized=romanized))
    except LoanWordAlreadyExist:
      print('word already exist in db')
    else:
      print('word added successfully')

  @Slot()
  def __do_quit(self):
    print('quit')
    self.close()

def main():
  ap = ArgumentParser()

  ap.add_argument('--dictionary-file', '-f', required=True)
  ap.add_argument('--loan-dictionary', '-l', required=True)

  args = ap.parse_args()

  nwl = load_normal_words(args.dictionary_file)
  lwl = load_loan_words(args.loan_dictionary)

  app = QApplication()
  dv = DictViewer(nwl, args.dictionary_file, lwl, args.loan_dictionary)
  dv.show()
  app.exec()

main()
