#!/usr/bin/env python

import argparse
from argparse import ArgumentParser

from dropout_fontconfig import (
  FcPatternCreate,
  FcMatchKind,
  FC_FAMILY,
  FcPatternAddString,
  FcConfigSubstitute,
  FcConfigSetDefaultSubstitute,
  FcFontMatch,
  FC_FILE,
  FcPatternGetString,
  FC_INDEX,
  FcPatternGetInteger,
)
from annotation_file import annotation_parse
from dropout_freetype import FT_Init_FreeType, FT_New_Face, FT_Sfnt_Tag, FT_Get_Sfnt_Table
from PySide6.QtGui import QGuiApplication, QFont, QFontMetrics
from loan_word_db import load_loan_words, LoanWordList
from normal_word_db import load_normal_words, NormalWordList

def main():
  ap = ArgumentParser()

  ap.add_argument('annotation_file')
  ap.add_argument('--ass-file', '-o', type=argparse.FileType('w'), required=True)
  ap.add_argument('--font-name', default='Noto Sans CJK JP')
  ap.add_argument('--font-size', type=int, default=57)
  ap.add_argument('--video-x', type=int, default=1920)
  ap.add_argument('--video-y', type=int, default=1080)
  ap.add_argument('--margin-y', type=float, default=48.75)
  ap.add_argument('--outline-size', type=float, default=2.5)
  ap.add_argument('--rubi-outline-size', type=float, default=2.0)
  ap.add_argument('--loans-blacklist', '-l')
  ap.add_argument('--word-blacklist', '-w')
  ap.add_argument('--no-rubi', '-n', action='store_true')
  ap.add_argument('--no-loans', '-L', action='store_true')

  args = ap.parse_args()

  rubi_font_size = args.font_size // 2

  with open(args.annotation_file, 'r') as f:
    af = annotation_parse(f.read())

  if args.loans_blacklist is None:
    lwl = LoanWordList(count_known=True)
  else:
    lwl = load_loan_words(args.loans_blacklist, count_known=True)

  if args.word_blacklist is None:
    nwl = NormalWordList(count_known=True)
  else:
    nwl = load_normal_words(args.word_blacklist, count_known=True)

  pattern = FcPatternCreate()
  FcPatternAddString(pattern, FC_FAMILY, args.font_name)

  FcConfigSubstitute(None, pattern, FcMatchKind.Pattern)
  FcConfigSetDefaultSubstitute(None, pattern)

  m = FcFontMatch(None, pattern)
  if m is None:
    ap.error('cant find font')

  font_path = FcPatternGetString(m, FC_FILE, 0)
  font_idx = FcPatternGetInteger(m, FC_INDEX, 0)

  ft = FT_Init_FreeType()
  face = FT_New_Face(ft, font_path, font_idx)
  os2 = FT_Get_Sfnt_Table(face, FT_Sfnt_Tag.OS2)

  app = QGuiApplication()

  font = QFont()

  font.setFamily(args.font_name)
  font.setPixelSize(face.contents.units_per_EM)
  font.setHintingPreference(QFont.HintingPreference.PreferNoHinting)

  metrics = QFontMetrics(font)

  print('[Script Info]', file=args.ass_file)
  print('ScriptType: v4.00+', file=args.ass_file)
  print('ScaledBorderAndShadow: yes', file=args.ass_file)
  print(f'PlayResX: {args.video_x}', file=args.ass_file)
  print(f'PlayResY: {args.video_y}', file=args.ass_file)
  print('Kerning: yes', file=args.ass_file)

  print('[V4+ Styles]', file=args.ass_file)
  print('Format: Name, Fontname, Fontsize, PrimaryColour, OutlineColour, Spacing, BorderStyle, Outline, Shadow, Alignment, Encoding', file=args.ass_file)
  print(f'Style: Default,{args.font_name},{args.font_size},&H00FFFFFF,&H00000000,0,1,{args.outline_size:.1f},0,7,1', file=args.ass_file)
  print(f'Style: Rubi,{args.font_name},{rubi_font_size},&H00FFFFFF,&H00000000,0,1,{args.rubi_outline_size:.1f},0,7,1', file=args.ass_file)

main()
