#!/usr/bin/env python

import argparse
from argparse import ArgumentParser

from dropout_fontconfig import (
  FcPatternCreate,
  FcMatchKind,
  FC_FAMILY,
  FcPatternAddString,
  FcConfigSubstitute,
  FcConfigSetDefaultSubstitute,
  FcFontMatch,
)
from annotation_file import annotation_parse

def main():
  ap = ArgumentParser()

  ap.add_argument('annotation_file')
  ap.add_argument('--ass-file', '-o', type=argparse.FileType('w'), required=True)
  ap.add_argument('--font-name', default='Noto Sans CJK JP')
  ap.add_argument('--font-size', type=int, default=57)
  ap.add_argument('--video-x', type=int, default=1920)
  ap.add_argument('--video-y', type=int, default=1080)
  ap.add_argument('--margin-y', type=float, default=48.75)
  ap.add_argument('--outline-size', type=float, default=2.5)

  args = ap.parse_args()

  with open(args.annotation_file, 'r') as f:
    af = annotation_parse(f.read())

  pattern = FcPatternCreate()
  FcPatternAddString(pattern, FC_FAMILY, args.font_name)

  FcConfigSubstitute(None, pattern, FcMatchKind.Pattern)
  FcConfigSetDefaultSubstitute(None, pattern)

  m = FcFontMatch(None, pattern)
  if m is None:
    ap.error('cant find font')

  print('[Script Info]', file=args.ass_file)
  print('ScriptType: v4.00+', file=args.ass_file)
  print('ScaledBorderAndShadow: yes', file=args.ass_file)
  print(f'PlayResX: {args.video_x}', file=args.ass_file)
  print(f'PlayResY: {args.video_y}', file=args.ass_file)

  print('[V4+ Styles]', file=args.ass_file)
  print('Format: Name, Fontname, Fontsize, PrimaryColour, OutlineColour, BorderStyle, Outline, Shadow, Alignment, Encoding', file=args.ass_file)
  print(f'Style: Default,{args.font_name},{args.font_size},&H00FFFFFF,&H00000000,1,{args.outline_size},0,7,1', file=args.ass_file)

main()
