#!/usr/bin/env python

"""a subtitle converter that generates ASS.

   this was bornt because Aegisub's "karaoke templater"
    (yes, it can be used for things other than lyrics if you set karaoke timing to zero)
    doesn't work with line breaks and doesn't stack subtitles.

   we want this for ordinary furigana / ruby texts to work in Mpv.
   so this program has a mini layout engine which should implement the features we need.

   it has a dependency on Qt because it's much more easy to just use shaping engine from it.
    (Aegisub uses wxWidgets similarly to measure texts for its "karaoke templater".)"""

import argparse
from argparse import ArgumentParser

from dropout_fontconfig import (
  FcPatternCreate,
  FcMatchKind,
  FC_FAMILY,
  FcPatternAddString,
  FcConfigSubstitute,
  FcConfigSetDefaultSubstitute,
  FcFontMatch,
  FC_FILE,
  FcPatternGetString,
  FC_INDEX,
  FcPatternGetInteger,
)
from annotation_file import annotation_parse, PlainAnnotation, LoanAnnotation, KanjiAnnotation, AnnotationFile
from dropout_freetype import FT_Init_FreeType, FT_New_Face, FT_Sfnt_Tag, FT_Get_Sfnt_Table, TT_OS2
from PySide6.QtGui import QGuiApplication, QFont, QFontMetrics
from loan_word_db import load_loan_words, LoanWordList
from normal_word_db import load_normal_words, NormalWordList
from dataclasses import dataclass
from abc import ABC, abstractmethod
from typing import override
from enum import Enum
import enum
from typing import TextIO
from manifest_file import manifest_load

@dataclass
class AssLine:
  text: str

  # whether or not should use the Rubi style
  is_rubi: bool = False

  # coordinates in pixels
  x: float = 0.0
  y: float = 0.0

class LayoutObject(ABC):
  """an object that take a rectangular space."""

  @abstractmethod
  def to_ass(self) -> list[AssLine]:
    """return list of ASS lines needed to render contents in this layout object.
       coordinates are relative to top-left corner of rect of this layout object.

       this function assumes the global position of top-left corner of this layout object is at (0, 0)."""

  def get_advance(self) -> float:
    """return x offset suitable for placing next layout object.
       this is width plus extra post spacing."""
    return self.get_width()

  @abstractmethod
  def get_width(self) -> float:
    """return logical width, without extra spacings on each end."""

  @abstractmethod
  def get_height(self) -> float:
    pass

  def get_pre_spacing(self) -> float:
    """extra spacing that should be added before placing this layout object when layouting."""
    return 0.0

@dataclass
class LayouterContext:
  """a wrapper class
     making it easy to pass all these in one argument."""

  os2: TT_OS2
  font_size: int
  rubi_font_size: int
  fm: QFontMetrics

_ASCII_SPC = ' '

class SimpleTextObject(LayoutObject):
  """simplest case containing exactly just one text."""

  def __init__(self, ctx: LayouterContext, text: str, is_rubi: bool = False):
    assert text != '', '???'
    self.__ctx = ctx
    self.__is_rubi = is_rubi
    self.__width = self.__measure_text(text)
    assert self.__width > 0, '???'
    self.__text = text

  def __measure_text(self, s: str) -> float:
    # font size value in ASS means ascender plus descender in pixels, not the pixel size of EM square.
    # another catch is it always uses ascender and descender sizes from OS/2 table.
    #
    # note that we have previously configured QFontMetrics to return us values in font units instead of in pixels.
    #
    # this formula is simple: Qt does shaping and return us advance value in font units,
    #                          then we find out how many ascender plus descender is in that,
    #                          since ASS font size means ascender plus descender in pixels,
    #                          if we then multiply it with the ASS font size value we get the advance value in pixels.
    #
    # this is a bit neat because we can use a single QFont but re-use it to measure using as many as different font sizes we want.
    #
    # we have been keeping all values in integers until this single division step, so accuracy here should be best-effort.
    #
    # XXX: using Qt to shape seem to return a slightly different result compared to HarfBuzz... (sub-pixel difference)
    return (self.__ctx.fm.horizontalAdvance(s) * (self.__ctx.rubi_font_size if self.__is_rubi else self.__ctx.font_size)) / (self.__ctx.os2.usWinAscent + self.__ctx.os2.usWinDescent)

  def get_text(self) -> str:
    return self.__text

  @override
  def to_ass(self) -> list[AssLine]:
    """we don't render each characters separately, this saves us output file size and
        avoids problem like outline collisions when the text is too small and are too close to each others (e.g. Rubi)
       this is similar to what Aegisub's karaoke templater produces."""

    ass_lines = [AssLine(text=self.__text, is_rubi=self.__is_rubi)]

    no_leading_spc = self.__text.lstrip(_ASCII_SPC)
    if no_leading_spc != self.__text:
      # ASS doesn't like leading/trailing spaces and ignores them completely
      # for leading spaces we must fixup by shifting text position to the right
      n_leading_spc = len(self.__text) - len(no_leading_spc)
      shift_ass_lines(ass_lines, self.__measure_text(_ASCII_SPC * n_leading_spc), 0.0)

    return ass_lines

  @override
  def get_width(self) -> float:
    return self.__width

  @override
  def get_height(self) -> float:
    if self.__is_rubi:
      return float(self.__ctx.rubi_font_size)

    return float(self.__ctx.font_size)

def shift_ass_lines(ass_lines: list[AssLine], delta_x: float, delta_y: float) -> list[AssLine]:
  for ass_line in ass_lines:
    ass_line.x += delta_x
    ass_line.y += delta_y
  return ass_lines

_KATAKANA_MAP: dict[str, str] = {
  'ァ': 'ｧ', 'ア': 'ｱ',
  'ィ': 'ｨ', 'イ': 'ｲ',
  'ゥ': 'ｩ', 'ウ': 'ｳ',
  'ェ': 'ｪ', 'エ': 'ｴ',
  'ォ': 'ｫ', 'オ': 'ｵ',
  'カ': 'ｶ', 'ガ': 'ｶﾞ',
  'キ': 'ｷ', 'ギ': 'ｷﾞ',
  'ク': 'ｸ', 'グ': 'ｸﾞ',
  'ケ': 'ｹ', 'ゲ': 'ｹﾞ',
  'コ': 'ｺ', 'ゴ': 'ｺﾞ',
  'サ': 'ｻ', 'ザ': 'ｻﾞ',
  'シ': 'ｼ', 'ジ': 'ｼﾞ',
  'ス': 'ｽ', 'ズ': 'ｽﾞ',
  'セ': 'ｾ', 'ゼ': 'ｾﾞ',
  'ソ': 'ｿ', 'ゾ': 'ｿﾞ',
  'タ': 'ﾀ', 'ダ': 'ﾀﾞ',
  'チ': 'ﾁ', 'ヂ': 'ﾁﾞ',
  'ッ': 'ｯ', 'ツ': 'ﾂ', 'ヅ': 'ﾂﾞ',
  'テ': 'ﾃ', 'デ': 'ﾃﾞ',
  'ト': 'ﾄ', 'ド': 'ﾄﾞ',
  'ナ': 'ﾅ', 'ニ': 'ﾆ', 'ヌ': 'ﾇ', 'ネ': 'ﾈ', 'ノ': 'ﾉ',
  'ハ': 'ﾊ', 'バ': 'ﾊﾞ', 'パ': 'ﾊﾟ',
  'ヒ': 'ﾋ', 'ビ': 'ﾋﾞ', 'ピ': 'ﾋﾟ',
  'フ': 'ﾌ', 'ブ': 'ﾌﾞ', 'プ': 'ﾌﾟ',
  'ヘ': 'ﾍ', 'ベ': 'ﾍﾞ', 'ペ': 'ﾍﾟ',
  'ホ': 'ﾎ', 'ボ': 'ﾎﾞ', 'ポ': 'ﾎﾟ',
  'マ': 'ﾏ', 'ミ': 'ﾐ', 'ム': 'ﾑ', 'メ': 'ﾒ', 'モ': 'ﾓ',
  'ャ': 'ｬ', 'ヤ': 'ﾔ',
  'ュ': 'ｭ', 'ユ': 'ﾕ',
  'ョ': 'ｮ', 'ヨ': 'ﾖ',
  'ラ': 'ﾗ', 'リ': 'ﾘ', 'ル': 'ﾙ', 'レ': 'ﾚ', 'ロ': 'ﾛ',
  'ワ': 'ﾜ', 'ヲ': 'ｦ',
  'ン': 'ﾝ',
  'ヴ': 'ｳﾞ', 'ヷ': 'ﾜﾞ', 'ヺ': 'ｦﾞ',
  'ー': 'ｰ',
}

def full_to_half(s: str) -> str:
  return ''.join(map(lambda c: _KATAKANA_MAP[c], s))

class LoanwordTextObject(LayoutObject):
  """a loanword with a label centered on top of it.

     width of this object is always the same as base text,
     the label can thus extend outside.
     spacings is returned when asked if the label is longer."""

  def __init__(self, ctx: LayouterContext, base: str, romanized: str):
    """this expect passing katakana in full-width as argument.
       it will be converted into half-width automatically."""

    self.__label_txt_obj = SimpleTextObject(ctx=ctx, text=romanized, is_rubi=True)
    self.__base_txt_obj = SimpleTextObject(ctx=ctx, text=full_to_half(base))

    if self.__label_txt_obj.get_width() > self.__base_txt_obj.get_width():
      self.__spacing = (self.__label_txt_obj.get_width() - self.__base_txt_obj.get_width()) / 2
    else:
      self.__spacing = 0

  @override
  def get_pre_spacing(self) -> float:
    return self.__spacing

  @override
  def get_advance(self) -> float:
    return self.__base_txt_obj.get_width() + self.__spacing

  @override
  def get_width(self) -> float:
    return self.__base_txt_obj.get_width()

  @override
  def get_height(self) -> float:
    return self.__label_txt_obj.get_height() + self.__base_txt_obj.get_height()

  @override
  def to_ass(self) -> list[AssLine]:
    label_al = self.__label_txt_obj.to_ass()
    # center of base is also center of label
    shift_ass_lines(label_al, self.__base_txt_obj.get_width() / 2, 0.0)
    shift_ass_lines(label_al, -(self.__label_txt_obj.get_width() / 2), 0.0)

    base_al = shift_ass_lines(self.__base_txt_obj.to_ass(), 0.0, self.__label_txt_obj.get_height())

    return label_al + base_al

class FuriganaMode(Enum):
  # should render furigana as a single ASS line and center it
  CENTER = enum.auto()

  # should render each furigana character as separate ASS line and use spacings in between
  INTERNAL_SPACING = enum.auto()

class TextWithRubiObject(LayoutObject):
  """One or more kanji characters with furigana on top."""

  def __init__(self, ctx: LayouterContext, base: str, reading: str):
    self.__ctx = ctx
    self.__label_txt_obj = SimpleTextObject(ctx=ctx, text=reading, is_rubi=True)
    self.__base_txt_obj = SimpleTextObject(ctx=ctx, text=base)

    if len(base) > 1 and len(reading) > 1 and self.__label_txt_obj.get_width() < self.__base_txt_obj.get_width():
      self.__mode = FuriganaMode.INTERNAL_SPACING
      self.__external_spacing = 0
    else:
      self.__mode = FuriganaMode.CENTER

      if self.__label_txt_obj.get_width() > self.__base_txt_obj.get_width():
        self.__external_spacing = (self.__label_txt_obj.get_width() - self.__base_txt_obj.get_width()) / 2
      else:
        self.__external_spacing = 0

  @override
  def get_height(self) -> float:
    return self.__label_txt_obj.get_height() + self.__base_txt_obj.get_height()

  @override
  def get_width(self) -> float:
    return self.__base_txt_obj.get_width()

  @override
  def get_advance(self) -> float:
    return self.__base_txt_obj.get_width() + self.__external_spacing

  @override
  def get_pre_spacing(self) -> float:
    return self.__external_spacing

  @override
  def to_ass(self) -> list[AssLine]:
    base_al = shift_ass_lines(self.__base_txt_obj.to_ass(), 0.0, self.__label_txt_obj.get_height())

    match self.__mode:
      case FuriganaMode.CENTER:
        # same approach as how we center loanword
        label_al = self.__label_txt_obj.to_ass()
        shift_ass_lines(label_al, self.__base_txt_obj.get_width() / 2, 0.0)
        shift_ass_lines(label_al, -(self.__label_txt_obj.get_width() / 2), 0.0)
      case FuriganaMode.INTERNAL_SPACING:
        label_al = []

        internal_spacing = (self.__base_txt_obj.get_width() - self.__label_txt_obj.get_width()) / (len(self.__label_txt_obj.get_text()) + 1)
        pen_x = internal_spacing

        for char in self.__label_txt_obj.get_text():
          char_txt_obj = SimpleTextObject(ctx=self.__ctx, text=char, is_rubi=True)

          label_al.extend(shift_ass_lines(char_txt_obj.to_ass(), pen_x, 0.0))

          pen_x += char_txt_obj.get_width() + internal_spacing
      case _:
        raise AssertionError('unreachable')

    return label_al + base_al

class SubtitleLineObject(LayoutObject):
  """a horizontal linear layout containing other layout objects.
     children start from left to right and are aligned at bottom.

     height of this layout object is the tallest child.

     the width of this layout object is
      total width of all children plus
      their spacing requirements,
      excluding pre-spacing of first child and post-spacing of last child.

    pre-spacing of this layout object is inherited from the first child,
    and post-spacing of this layout object is inherited from the last child.

    line wrapping is not implemented, as subtitles will use line breaks explictly."""

  def __init__(self, childs: list[LayoutObject]):
    self.__childs = childs
    assert len(childs) > 0, '???'

    self.__width = 0
    self.__height = -1

    for nth, child in enumerate(childs):
      if nth != 0:
        self.__width += child.get_pre_spacing()

      if nth == len(childs) - 1:
        self.__width += child.get_width()
      else:
        self.__width += child.get_advance()

      if child.get_height() > self.__height:
        self.__height = child.get_height()

  @override
  def get_pre_spacing(self) -> float:
    return self.__childs[0].get_pre_spacing()

  @override
  def get_height(self) -> float:
    return self.__height

  @override
  def get_width(self) -> float:
    return self.__width

  @override
  def get_advance(self) -> float:
    return self.__width + (self.__childs[-1].get_advance() - self.__childs[-1].get_width())

  @override
  def to_ass(self) -> list[AssLine]:
    pen_x = 0
    ass_lines = []

    for nth, child in enumerate(self.__childs):
      if nth != 0:
        pen_x += child.get_pre_spacing()

      ass_lines.extend(shift_ass_lines(child.to_ass(), pen_x, self.get_height() - child.get_height()))

      pen_x += child.get_advance()

    return ass_lines

@dataclass
class AbstractSubtitle:
  """a subtitle line with lane index associated to
      it that is ready for the final rendering."""

  # a lane is an abstarct row that can show subtitle on the screen.
  # the height of a lane is determined by maximum height of
  #  all subtitle lines allocated on that lane.
  #
  # this is used to prevent subtitles stacked on top having
  #  inconsistent Y level positions throughout a show depending on
  #  what's below it, which may look visually awkward,
  #  and other undesirable behaviors caused by variable heights.
  #  (e.g. a line w/o Rubi vs a line with Rubi, when the latter
  #         tries to reuse room left by the former, would otherwise fail.)
  lane_idx: int

  start: int
  end: int
  inner: SubtitleLineObject

def _format_ass_ts(ts: int) -> str:
  # ASS stores only first two of three digits in milliseconds field.
  # also, hours field is not padded with extra zero.

  tmp, ms = divmod(ts, 1000)
  tmp, secs = divmod(tmp, 60)
  hrs, mins = divmod(tmp, 60)

  # XXX: doing rounding can cause unintended
  #       stacking behavior that dont match with source input!
  return f'{hrs}:{mins:02}:{secs:02}.{ms // 10:02}'

@dataclass
class WriterContext:
  """something with similar purpose like LayouterContext."""

  video_x: int
  video_y: int
  margin_y: float
  ass_file: TextIO

class ASSWriter:
  """this class is a state machine,
     it positions subtitle lines on screen and does collision detection.
     it emits actual ASS events with calculated final pixel positions.

     currently, it only produces bottom-centered subtitle rendering."""

  def __init__(self, ctx: WriterContext):
    # note: lane 0 starts from bottom on the screen and grows upwards
    self.__lane_heights: list[float] = []
    self.__lane_occupied_until: list[int] = []
    self.__n_lanes = 0

    self.__current_time = -1

    self.__subtitles: list[AbstractSubtitle] = []
    self.__ctx = ctx

  def handle_sub_line(self, start: int, end: int, sub_line: SubtitleLineObject):
    """if two or more subtitles collide due to showing in same timing window,
       later-comer will be stacked on top.

       as soon as a subtitle goes out of its timing window,
       its rooms will be reused by other subtitles.

       timing arguments passed to this function must not go backward."""

    if start < self.__current_time:
      raise ValueError('time not sorted')

    # try to find a free lane that already exists
    for lane_idx, lane_occupied_until in enumerate(self.__lane_occupied_until):
      if start < lane_occupied_until:
        continue

      # found a room to re-use

      self.__lane_occupied_until[lane_idx] = end
      self.__subtitles.append(AbstractSubtitle(lane_idx=lane_idx, start=start, end=end, inner=sub_line))

      if self.__lane_heights[lane_idx] < sub_line.get_height():
        self.__lane_heights[lane_idx] = sub_line.get_height()

      break
    else:
      # couldnt find a free lane.
      # so allocate a new one and use it.
      self.__lane_occupied_until.append(end)
      self.__subtitles.append(AbstractSubtitle(lane_idx=self.__n_lanes, start=start, end=end, inner=sub_line))
      self.__n_lanes += 1
      self.__lane_heights.append(sub_line.get_height())

    self.__current_time = start

  def finish(self):
    for subtitle in self.__subtitles:
      # note that in stock ASS, even multi-line subtitles have each line centered. so we do the same thing.
      pos_x = (self.__ctx.video_x - subtitle.inner.get_width()) / 2
      # subtitle is aligned to the bottom of the lane it belongs to
      #
      # also note: it seems like stock ASS doesn't add any extra spacing between stacked subtitle lines. so as we.
      pos_y = self.__ctx.video_y - self.__ctx.margin_y - sum(self.__lane_heights[:subtitle.lane_idx]) - subtitle.inner.get_height()

      for ass_line in shift_ass_lines(subtitle.inner.to_ass(), pos_x, pos_y):
        print(f'Dialogue: {_format_ass_ts(subtitle.start)},{_format_ass_ts(subtitle.end)},{"Rubi" if ass_line.is_rubi else "Default"},{{\\pos({ass_line.x},{ass_line.y})}}{ass_line.text}', file=self.__ctx.ass_file)

@dataclass
class WriteOptions:
  no_rubi: bool
  no_loans: bool
  lwl: LoanWordList
  nwl: NormalWordList

def write_af(af: AnnotationFile, layout_ctx: LayouterContext, writer_ctx: WriterContext, opts: WriteOptions):
  # we need a new writer object for each AF
  # thats because we didnt sort lines by time
  #
  # if we will be writing multiple AFs from a manifest,
  #  the manifest loader already ensures there is no overlaps.
  writer = ASSWriter(ctx=writer_ctx)

  for js_dialogue in af.lines:
    sls = []
    los = []

    for js_annotation in js_dialogue.fragments:
      if isinstance(js_annotation.inner, PlainAnnotation):
        plain_texts = js_annotation.inner.text.split('\n')

        if len(plain_texts) > 1:
          for plain_text in plain_texts[:-1]:
            if plain_text != '':
              los.append(SimpleTextObject(ctx=layout_ctx, text=plain_text))

            assert len(los) > 0, 'fixme'
            sls.append(SubtitleLineObject(los))
            los = []

          if plain_texts[-1] != '':
            los.append(SimpleTextObject(ctx=layout_ctx, text=plain_texts[-1]))
        else:
          los.append(SimpleTextObject(ctx=layout_ctx, text=plain_texts[0]))
      elif isinstance(js_annotation.inner, LoanAnnotation):
        if opts.no_rubi or opts.no_loans or (js_annotation.inner.base, js_annotation.inner.romanized) in opts.lwl.known:
          los.append(SimpleTextObject(ctx=layout_ctx, text=full_to_half(js_annotation.inner.base)))
        else:
          los.append(LoanwordTextObject(ctx=layout_ctx, base=js_annotation.inner.base, romanized=js_annotation.inner.romanized))
      elif isinstance(js_annotation.inner, KanjiAnnotation):
        for chars in js_annotation.inner.fragments:
          if opts.no_rubi or (chars.base, chars.reading) in opts.nwl.known:
            los.append(SimpleTextObject(ctx=layout_ctx, text=chars.base))
          else:
            los.append(TextWithRubiObject(ctx=layout_ctx, base=chars.base, reading=chars.reading))
      else:
        raise AssertionError('unhandled annotation type')

    assert len(los) > 0, 'fixme'
    sls.append(SubtitleLineObject(los))

    # in multi-line sub the order is from top to bottom.
    # however, writer use bottom-to-top.
    # thus the reversed order here.
    for sub_line in reversed(sls):
      writer.handle_sub_line(start=js_dialogue.start_time, end=js_dialogue.end_time, sub_line=sub_line)

  writer.finish()

class InputType(Enum):
  AF = enum.auto()
  MANIFEST = enum.auto()

def main():
  ap = ArgumentParser()

  ap.add_argument('input_file', help='this can either be a .annotations or .manifest')
  ap.add_argument('--ass-file', '-o', type=argparse.FileType('w'), required=True)

  # we chose this as default because our main supported platforms (Linux and Android) should often have them.
  ap.add_argument('--font-name', default='Noto Sans CJK JP')

  # this doesn't matter. libass scales if player resolution doesnt match subtitle's.
  ap.add_argument('--video-x', type=int, default=1920)
  ap.add_argument('--video-y', type=int, default=1080)

  # these are just some defaults that kinda replicate default rendering result when u load an SRT subtitles into MPV.
  ap.add_argument('--font-size', type=int, default=57)
  ap.add_argument('--margin-y', type=float, default=48.75)
  ap.add_argument('--outline-size', type=float, default=2.5)
  ap.add_argument('--shadow-size', type=float, default=0.0)
  ap.add_argument('--rubi-shadow-size', type=float, default=0.0)

  # except this, i have no reference to borrow the value from.
  # it seems setting it to half of outline_size looks ugly.
  # same if i set it to same value as outline_size.
  # so i just tweaked a bit, this value seems to look somewhat fine at least.
  ap.add_argument('--rubi-outline-size', type=float, default=2.0)

  ap.add_argument('--loans-blacklist', '-l')
  ap.add_argument('--word-blacklist', '-w')
  ap.add_argument('--no-rubi', '-n', action='store_true')
  ap.add_argument('--no-loans', '-L', action='store_true')

  args = ap.parse_args()

  rubi_font_size = args.font_size // 2

  if args.input_file.endswith('.annotations'):
    input_type = InputType.AF
    with open(args.input_file, 'r') as f:
      af = annotation_parse(f.read())
  elif args.input_file.endswith('.manifest'):
    input_type = InputType.MANIFEST
    mf = manifest_load(args.input_file)
  else:
    ap.error('i dont understand your input file extension!')

  if args.loans_blacklist is None:
    lwl = LoanWordList(count_known=True)
  else:
    lwl = load_loan_words(args.loans_blacklist, count_known=True)

  if args.word_blacklist is None:
    nwl = NormalWordList(count_known=True)
  else:
    nwl = load_normal_words(args.word_blacklist, count_known=True)

  # user gives us a font family string,
  #  but because we need to read some parameters of the font using FreeType later,
  #  we want the underlying font file path and face index within it,
  #  so we ask fontconfig to deal with it for us.

  pattern = FcPatternCreate()
  FcPatternAddString(pattern, FC_FAMILY, args.font_name)

  FcConfigSubstitute(None, pattern, FcMatchKind.Pattern)
  FcConfigSetDefaultSubstitute(None, pattern)

  m = FcFontMatch(None, pattern)
  if m is None:
    ap.error('cant find font')

  font_path = FcPatternGetString(m, FC_FILE, 0)
  font_idx = FcPatternGetInteger(m, FC_INDEX, 0)

  ft = FT_Init_FreeType()
  face = FT_New_Face(ft, font_path, font_idx)
  os2 = FT_Get_Sfnt_Table(face, FT_Sfnt_Tag.OS2)

  app = QGuiApplication()

  font = QFont()

  font.setFamily(args.font_name)

  # note: "point size" is irrelevant because ASS font sizes are in pixels
  # we can't directly set the pixel size because
  #  Qt wants size of EM square in pixels but ASS uses OS/2 ascender plus descender in pixels.
  # it is possible to calculate how big is EM square and set it here
  # but since we can only feed it an integer it will cause a lot of errors.
  #
  # I haven't found a documented way to let Qt return values in font units directly
  # so I had to use some trick
  #
  # scalable fonts (which is the only type of font we support) internally use "font units" instead of pixels
  # when you set a pixel font size, you're saying how big the EM square is in pixels.
  # it then uses it to calculate a factor for converting everything font unit into pixels when it needs.
  # the formula it uses is simple: scale = EM size in pixels / EM size in font units (this part is quoted from FreeType documentation)
  # so if we set font size to EM size in font units we effectively nullify the scaling.
  # so that all measurements returned now should be in font units.
  # XXX: i have no idea what side effects this can give, though.
  font.setPixelSize(face.contents.units_per_EM)

  # hinting seems to be disabled by default in libass. (and its only exposed through API, i.e. not possible to control in subtitle files)
  # Qt enables hinting on some platforms so it is correct to explicitly disable it.
  # (but doesn't hinting already do nothing since EM size in font units equals EM size in pixels? font units are indivisible.)
  font.setHintingPreference(QFont.HintingPreference.PreferNoHinting)

  # kerning is enabled by default as per Qt documentation.

  # don't disable ligature, because it's a thing in ASS (as long as Spacing in ASS style is zero).

  metrics = QFontMetrics(font)

  print('[Script Info]', file=args.ass_file)
  print('ScriptType: v4.00+', file=args.ass_file)

  # the Aegisub documentation says that you should always enable this. (sometimes its not enabled by default with libass.)
  print('ScaledBorderAndShadow: yes', file=args.ass_file)

  print(f'PlayResX: {args.video_x}', file=args.ass_file)
  print(f'PlayResY: {args.video_y}', file=args.ass_file)
  # kerning is a libass extension to ASS and is disabled by default,
  # but we want to benefit from more compact text for subtitles, so we enable it here.
  print('Kerning: yes', file=args.ass_file)

  print('[V4+ Styles]', file=args.ass_file)

  # libass supports custom Format headers and we can omit fields and it still initializes with valid default values.
  # XXX: it confuses Aegisub and doesn't load in there. however, it doesn't break playback within user's video players because they use libass.
  print('Format: Name, Fontname, Fontsize, PrimaryColour, OutlineColour, Spacing, BorderStyle, Outline, Shadow, Alignment, Encoding', file=args.ass_file)

  # TODO: make more style settings customiziable
  #
  # `7' in Alignment means absolete coordinates are anchored by top-left corner (our ASS writer produces that)
  # it actually means the start of horizontal advance of first character and ascender. (which matches with what our layout engine impl currently think)
  # this doesn't have any meaning for subtitles alignments however any more, as its completely bypassed by saying absolute coordinates
  # (note it's also why we are omitting Margin* values here.)
  # the collision detection (subtitle stacking) and centering is done on our behave in the ASSWriter class.
  # this is because ASS doesn't support Rubi natively, so as a workaround, we have to do this to be able to position Rubi texts manually
  print(f'Style: Default,{args.font_name},{args.font_size},&H00FFFFFF,&H00000000,0,1,{args.outline_size:.1f},{args.shadow_size:.1f},7,1', file=args.ass_file)
  print(f'Style: Rubi,{args.font_name},{rubi_font_size},&H00FFFFFF,&H00000000,0,1,{args.rubi_outline_size:.1f},{args.rubi_shadow_size:.1f},7,1', file=args.ass_file)

  print('[Events]', file=args.ass_file)
  # we don't need "Layer" field, it seems that stacking is already bypassed by saying absolute coordinates
  print('Format: Start, End, Style, Text', file=args.ass_file)

  layout_ctx = LayouterContext(os2=os2, font_size=args.font_size, rubi_font_size=rubi_font_size, fm=metrics)
  writer_ctx = WriterContext(video_x=args.video_x, video_y=args.video_y, margin_y=args.margin_y, ass_file=args.ass_file)
  opts = WriteOptions(no_rubi=args.no_rubi, no_loans=args.no_loans, lwl=lwl, nwl=nwl)

  match input_type:
    case InputType.AF:
      write_af(af=af, layout_ctx=layout_ctx, writer_ctx=writer_ctx, opts=opts)
    case InputType.MANIFEST:
      for af in mf.afs:
        write_af(af=af, layout_ctx=layout_ctx, writer_ctx=writer_ctx, opts=opts)
    case _:
      raise AssertionError

main()
