#!/usr/bin/env python

# take an existing ASS subtitle file and
# convert it into Annotation File format

import argparse
from dropout_ass import dropout_parse_ass
from annotation_file import (
  AnnotationFile,
  DialogueLine,
  Annotation,
  PlainAnnotation,
  annotation_save,
)

def main():
  ap = argparse.ArgumentParser()

  ap.add_argument('sub_file', type=argparse.FileType('r'))
  ap.add_argument('--annotation-file', '-o', type=argparse.FileType('w'), required=True)

  args = ap.parse_args()

  af = AnnotationFile()

  for subtitle in dropout_parse_ass(args.sub_file.read()):
    af.lines.append(DialogueLine(fragments=[Annotation(PlainAnnotation(subtitle.text), unfinished=True)], start_time=subtitle.timing[0], end_time=subtitle.timing[1]))

  af.validate()

  args.annotation_file.write(annotation_save(af))
  args.annotation_file.write('\n')

main()
