#!/usr/bin/env python

# take an existing SRT subtitle file and
# convert it into Annotation File format

import argparse
from dropout_srt import dropout_parse_srt
from annotation_file import (
  AnnotationFile,
  DialogueLine,
  Annotation,
  PlainAnnotation,
  annotation_save,
)

def main():
  ap = argparse.ArgumentParser()

  ap.add_argument('sub_file', type=argparse.FileType('r'))
  ap.add_argument('--annotation-file', '-o', type=argparse.FileType('w'), required=True)

  args = ap.parse_args()

  af = AnnotationFile()

  for line in dropout_parse_srt(args.sub_file.read()):
    af.lines.append(DialogueLine([Annotation(PlainAnnotation(line), unfinished=True)]))

  af.validate()

  args.annotation_file.write(annotation_save(af))
  args.annotation_file.write('\n')

main()
