#!/usr/bin/env python
import argparse
from argparse import ArgumentParser
from annotation_file import (
  annotation_parse,
  PlainAnnotation,
  LoanAnnotation,
  KanjiAnnotation,
)
import html
from loan_word_db import load_loan_words, LoanWordList
from normal_word_db import load_normal_words, NormalWordList

def main():
  ap = ArgumentParser()

  ap.add_argument('annotation_file', type=argparse.FileType('r'))
  ap.add_argument('--html-file', '-o', type=argparse.FileType('w'), required=True)
  ap.add_argument('--loans-blacklist', '-l')
  ap.add_argument('--word-blacklist', '-w')
  ap.add_argument('--no-labeling', '-n', action='store_true', help='disable all furigana')

  args = ap.parse_args()

  af = annotation_parse(args.annotation_file.read())

  if args.loans_blacklist:
    lwl = load_loan_words(args.loans_blacklist)
  else:
    lwl = LoanWordList()

  if args.word_blacklist:
    nwl = load_normal_words(args.word_blacklist, count_known=True)
  else:
    nwl = NormalWordList(count_known=True)

  print('<!doctype html>', file=args.html_file)
  print('<html lang="ja">', file=args.html_file)
  print('<head>', file=args.html_file)
  print('<meta charset="utf-8"/>', file=args.html_file)
  print('<meta name="viewport" content="width=device-width"/>', file=args.html_file)
  print('</head>', file=args.html_file)
  print('<body>', file=args.html_file)

  for line in af.lines:
    args.html_file.write('<p>')

    for annotation in line.fragments:
      if isinstance(annotation.inner, PlainAnnotation):
        args.html_file.write(f'<span>{html.escape(annotation.inner.text)}</span>')
      elif isinstance(annotation.inner, LoanAnnotation):
        if args.no_labeling or annotation.inner.base in lwl.inner:
          args.html_file.write(f'<span>{html.escape(annotation.inner.base)}</span>')
        else:
          args.html_file.write(f'<ruby>{html.escape(annotation.inner.base)}<rt>{html.escape(annotation.inner.romanized)}</ruby>')
      elif isinstance(annotation.inner, KanjiAnnotation):
        args.html_file.write('<span>')
        for chars in annotation.inner.fragments:
          if args.no_labeling or (chars.base, chars.reading) in nwl.known:
            args.html_file.write(f'<span>{html.escape(chars.base)}</span>')
          else:
            args.html_file.write(f'<ruby>{html.escape(chars.base)}<rt>{html.escape(chars.reading)}</ruby>')
        args.html_file.write('</span>')
      else:
        raise AssertionError('unhandled annotation type')

    print('</p>', file=args.html_file)

  print('</body>', file=args.html_file)
  print('</html>', file=args.html_file)

main()
